// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC52gkOOKSj84dhCo3mHqetKpZw6nbBDy0',
    appId: '1:412394991690:web:5242ddf3cb57fea8f8b6b3',
    messagingSenderId: '412394991690',
    projectId: 'chatapp-5f9c8',
    authDomain: 'chatapp-5f9c8.firebaseapp.com',
    storageBucket: 'chatapp-5f9c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8cqdUWTG5XIbozk7Tr-YPXo0D16fPOTQ',
    appId: '1:412394991690:android:2534542e4ed571d8f8b6b3',
    messagingSenderId: '412394991690',
    projectId: 'chatapp-5f9c8',
    storageBucket: 'chatapp-5f9c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjkgatAAvKdMqDRHxYygYanQ5Qs925FBI',
    appId: '1:412394991690:ios:2b831416c0083afaf8b6b3',
    messagingSenderId: '412394991690',
    projectId: 'chatapp-5f9c8',
    storageBucket: 'chatapp-5f9c8.appspot.com',
    iosBundleId: 'com.example.minimalChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjkgatAAvKdMqDRHxYygYanQ5Qs925FBI',
    appId: '1:412394991690:ios:6823e26fd961cf0ef8b6b3',
    messagingSenderId: '412394991690',
    projectId: 'chatapp-5f9c8',
    storageBucket: 'chatapp-5f9c8.appspot.com',
    iosBundleId: 'com.example.minimalChat.RunnerTests',
  );
}
